from flask import Blueprint, jsonify, session, send_file
from app.models import Note, User
from app import db
from fpdf import FPDF
from fpdf.enums import XPos, YPos
import datetime
import tempfile
import os

export_bp = Blueprint('export', __name__)


def login_required(f):
    from functools import wraps

    @wraps(f)
    def decorated_function(*args, **kwargs):
        if 'user_id' not in session:
            return jsonify({"error": "Authentication required"}), 401
        return f(*args, **kwargs)
    return decorated_function


@export_bp.route('/download-notes', methods=['GET'])
@login_required
def download_notes():
    user_id = session['user_id']
    user = db.session.get(User, user_id)
    notes = Note.query.filter_by(user_id=user_id) \
        .order_by(Note.note_date.desc()).all()

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    primary_blue = (26, 115, 232)
    text_gray = (40, 40, 40)
    light_gray = (120, 120, 120)
    soft_bg = (245, 247, 250)

    pdf.set_font("Helvetica", "B", 22)
    pdf.set_text_color(*primary_blue)
    pdf.cell(
        0, 15, f"{user.username}'s Notes",
        align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT
    )

    pdf.set_font("Helvetica", "I", 11)
    pdf.set_text_color(*light_gray)
    current_time = datetime.datetime.now().strftime(
        "Generated on %B %d, %Y at %I:%M %p"
    )
    pdf.cell(
        0, 8, current_time, align="C",
        new_x=XPos.LMARGIN, new_y=YPos.NEXT
    )

    pdf.set_draw_color(*primary_blue)
    pdf.set_line_width(1)
    pdf.line(25, pdf.get_y() + 5, 185, pdf.get_y() + 5)
    pdf.ln(15)

    if not notes:
        pdf.set_font("Helvetica", "", 12)
        pdf.set_text_color(*light_gray)
        pdf.cell(
            0, 10, "You have no saved notes yet.",
            align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT
        )
    else:
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(*text_gray)
        pdf.cell(
            0, 10, f"Total Notes: {len(notes)}",
            new_x=XPos.LMARGIN, new_y=YPos.NEXT
        )
        pdf.ln(8)

        for i, note in enumerate(notes, 1):
            if pdf.get_y() > 250:
                pdf.add_page()

            pdf.set_fill_color(*soft_bg)
            pdf.set_draw_color(*primary_blue)
            y_start = pdf.get_y()
            pdf.rect(20, y_start, 170, 12, style="F")

            pdf.set_font("Helvetica", "BI", 13)
            pdf.set_text_color(*text_gray)
            clean_title = note.topic.encode(
                'ascii', 'replace'
            ).decode('ascii').replace('?', '')
            pdf.set_xy(25, y_start + 2)
            pdf.cell(0, 8, f"{i}. {clean_title}")

            pdf.set_font("Helvetica", "I", 10)
            pdf.set_text_color(*light_gray)
            note_date = note.note_date.strftime("%b %d, %Y")
            pdf.set_xy(150, y_start + 2)
            pdf.cell(40, 8, note_date, align="R")

            pdf.ln(12)

            pdf.set_font("Helvetica", "", 11)
            pdf.set_text_color(*text_gray)
            clean_content = note.content.encode(
                'ascii', 'replace'
            ).decode('ascii').replace('?', '')

            pdf.set_fill_color(255, 255, 255)
            pdf.set_draw_color(230, 230, 230)
            pdf.set_line_width(0.3)
            pdf.set_x(25)
            pdf.multi_cell(160, 7, clean_content, border=1, fill=True)
            pdf.ln(10)

    pdf.set_y(-30)
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(*light_gray)
    pdf.cell(
        0, 10, "___________________________",
        align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT
    )

    footer_text = f"Total {len(notes)} note" + (
        "s" if len(notes) != 1 else ""
    )
    pdf.cell(0, 5, f"{footer_text} - Generated by DoDeck", align="C")

    temp_dir = tempfile.gettempdir()
    filename = f"{user.username}.pdf"
    filepath = os.path.join(temp_dir, filename)

    try:
        pdf.output(filepath)
        if not os.path.exists(filepath) or os.path.getsize(filepath) == 0:
            raise Exception("PDF file failed to generate")

        response = send_file(
            filepath,
            as_attachment=True,
            download_name=filename,
            mimetype='application/pdf'
        )

        @response.call_on_close
        def cleanup():
            if os.path.exists(filepath):
                os.remove(filepath)

        return response

    except Exception as e:
        print(f"Error creating PDF: {e}")
        if os.path.exists(filepath):
            os.remove(filepath)
        raise
